[workspace]
members = [
#    "common",
    "programs/soarchain-staking",
    "programs/soarchain-rewards"
]

[features]
resolution = true
skip-lint = false

[provider]
cluster = "Localnet"
wallet = "/home/alp/.config/solana/soarMN9ky6JHALASZPNEmg4yUVP34g25gSULxvHBXPX.json"

[programs.localnet]
soarchain_staking = "BjQHTqshCHuf6Zu7XK8jWiJnknMzi7exkRrLXioU4AK2"
soarchain_rewards = "UPSXdvWxwUTxMVkMtXLZhz2arCmx1uoc8c1z2V7Rf7S"

[registry]
url = "https://api.apr.dev"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
